# Generated by Django 5.0 on 2023-12-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='done',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
